example: stringex array list


stringex:
	g++ -std=c++0x -g -o string_test examples/string_ex.cpp


array:
	g++ -std=c++0x -g -o array_test examples/array.cpp	


list: #mylibs
	g++ -std=c++0x -Iinclude -g -Llibs -o list_test examples/list.cpp #libs/libsllist.a

# mylibs:
# 	g++ -std=c++0x -Iinclude -g -c src/sllist.cpp -o libs/sllist.o
# 	ar rc libs/libsllist.a libs/sllist.o
