example: tictactoe hanoi

.PHONY: tictactoe hanoi

tictactoe:
	g++ -std=c++0x -lPocoFoundation -lPocoNet -lboost_program_options -g -o tictactoe src/tictactoe.cpp

hanoi:
	g++ -std=c++0x -g -o hanoi src/thehanoitowers.cpp
